# --- Type (分類) ---
- name: "Type: Feature"
  color: "a2eeef"
  description: "新機能や改善"
- name: "Type: Bug"
  color: "d73a4a"
  description: "不具合やエラー"
- name: "Type: Task"
  color: "ededed"
  description: "雑多なタスク"
- name: "Type: Refactor"
  color: "f29513"
  description: "リファクタリング"
- name: "Type: Documentation"
  color: "0075ca"
  description: "ドキュメント関連"
- name: "Type: Question"
  color: "d876e3"
  description: "質問や議論"

# --- Priority (優先度) ---
- name: "Priority: Critical"
  color: "b60205"
  description: "緊急・最優先"
- name: "Priority: High"
  color: "d93f0b"
  description: "優先度：高"
- name: "Priority: Medium"
  color: "fbca04"
  description: "優先度：中"
- name: "Priority: Low"
  color: "0e8a16"
  description: "優先度：低"

# --- Status (状態) ---
- name: "Status: WIP"
  color: "f9d0c4"
  description: "作業中"
- name: "Status: Blocked"
  color: "000000"
  description: "他要因でブロック中"
- name: "Status: Review Needed"
  color: "c5def5"
  description: "レビュー待ち"
- name: "Status: Wontfix"
  color: "ffffff"
  description: "対応しない"

# --- Size (PRサイズ) ---
- name: "size: XS"
  color: "00ff00"
  description: "とても小さな変更 (<50行)"
- name: "size: S"
  color: "7fff00"
  description: "小さな変更 (<200行)"
- name: "size: M"
  color: "ffff00"
  description: "中程度の変更 (<500行)"
- name: "size: L"
  color: "ff8c00"
  description: "大きな変更 (<1000行)"
- name: "size: XL"
  color: "ff0000"
  description: "とても大きな変更 (1000行以上)"